using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using NE.Standard.UI.Graph;
using NE.Standard.UI.Shell.Localization;

namespace NE.Standard.UI.Web.Graph;

/// <summary>
/// The words the canvas's own chrome writes (picker, zoom bar, node parts), with their English; translated like the framework's
/// <c>UIStrings</c>.
/// </summary>
public sealed partial class GraphStrings : IUIStringsSource
{
    public const string Canvas = "ui.graph.canvas";
    public const string AddNode = UIGraphWords.AddNode;
    public const string SearchKinds = UIGraphWords.SearchKinds;
    public const string NoKinds = "ui.graph.no-kinds";
    public const string Categories = "ui.graph.categories";
    public const string AllKinds = "ui.graph.all-kinds";
    public const string Uncategorized = "ui.graph.uncategorized";
    public const string ZoomIn = "ui.graph.zoom-in";
    public const string ZoomOut = "ui.graph.zoom-out";
    public const string Fit = UIGraphWords.Fit;
    public const string Menu = "ui.graph.menu";
    public const string Minimap = "ui.graph.minimap";
    public const string Log = "ui.graph.log";
    public const string ClearLog = "ui.graph.clear-log";
    public const string LogEmpty = "ui.graph.log-empty";
    public const string RunProgress = "ui.graph.run-progress";
    public const string Run = "ui.graph.run";
    public const string RunAll = "ui.graph.run-all";
    public const string Stop = "ui.graph.stop";
    public const string RunLine = "ui.graph.run-line";
    public const string RunRequired = UIGraphWords.RunRequired;
    public const string RunStopped = UIGraphWords.RunStopped;
    public const string RunCycle = UIGraphWords.RunCycle;
    public const string FileProgress = UIGraphWords.FileProgress;
    public const string PinMany = "ui.graph.pin-many";
    public const string PinType = "ui.graph.pin-type";
    public const string TypeAny = "ui.graph.type-any";
    public const string TypeList = "ui.graph.type-list";
    public const string TypeListOf = "ui.graph.type-list-of";
    public const string TypeText = "ui.graph.type-text";
    public const string TypeNumber = "ui.graph.type-number";
    public const string TypeBoolean = "ui.graph.type-boolean";
    public const string TypeImage = "ui.graph.type-image";
    public const string TypeDate = "ui.graph.type-date";
    public const string TypeTime = "ui.graph.type-time";
    public const string TypeDateTime = "ui.graph.type-datetime";
    public const string Percent = "ui.graph.percent";
    public const string DisplayField = "ui.graph.display-field";
    public const string Collapse = "ui.graph.collapse";
    public const string Expand = "ui.graph.expand";
    public const string Pin = "ui.graph.pin";
    public const string Unpin = "ui.graph.unpin";
    public const string Group = "ui.graph.group";
    public const string NewNode = "ui.graph.new-node";
    public const string NewResource = "ui.graph.new-resource";
    public const string Recipe = "ui.graph.recipe";
    public const string Remove = UIGraphWords.Remove;
    public const string AddValue = UIGraphWords.AddValue;
    public const string ResetState = UIGraphWords.ResetState;
    public const string NoValue = "ui.graph.no-value";
    public const string More = UIGraphWords.More;
    public const string ChooseFile = UIGraphWords.ChooseFile;
    public const string AddParameter = UIGraphWords.AddParameter;
    public const string RemoveParameter = UIGraphWords.RemoveParameter;
    public const string ResetPin = UIGraphWords.ResetPin;
    public const string Parameters = "ui.graph.parameters";
    public const string ParametersEmpty = "ui.graph.parameters-empty";
    public const string ShowNode = "ui.graph.show-node";
    public const string UploadFailed = "ui.graph.upload-failed";
    public const string Unsaved = "ui.graph.unsaved";
    public const string Saving = "ui.graph.saving";
    public const string Plan = "ui.graph.plan";
    public const string PlanTargets = "ui.graph.plan-targets";
    public const string AddTarget = UIGraphWords.AddTarget;
    public const string SearchResources = UIGraphWords.SearchResources;
    public const string NoResources = "ui.graph.no-resources";
    public const string Target = UIGraphWords.Target;
    public const string Period = UIGraphWords.Period;
    public const string PeriodOnce = UIGraphWords.PeriodOnce;
    public const string PeriodMinute = UIGraphWords.PeriodMinute;
    public const string PeriodHour = UIGraphWords.PeriodHour;
    public const string Objective = UIGraphWords.Objective;
    public const string LeastRaw = UIGraphWords.LeastRaw;
    public const string LeastTime = UIGraphWords.LeastTime;
    public const string LeastCost = UIGraphWords.LeastCost;
    public const string PlanEmpty = "ui.graph.plan-empty";
    public const string PlanInfeasible = "ui.graph.plan-infeasible";
    public const string PlanUnsettled = "ui.graph.plan-unsettled";
    public const string PlanTotals = "ui.graph.plan-totals";
    public const string PlanBroughtIn = "ui.graph.plan-brought-in";
    public const string PlanResources = "ui.graph.plan-resources";
    public const string PlanCrafts = "ui.graph.plan-crafts";
    public const string PlanResource = "ui.graph.plan-resource";
    public const string PlanAmount = "ui.graph.plan-amount";
    public const string PlanMade = "ui.graph.plan-made";
    public const string PlanTaken = "ui.graph.plan-taken";
    public const string PlanLeft = "ui.graph.plan-left";
    public const string PlanRuns = "ui.graph.plan-runs";
    public const string PlanTime = "ui.graph.plan-time";
    public const string PlanWorkers = "ui.graph.plan-workers";
    public const string PlanAtOnce = "ui.graph.plan-at-once";
    public const string PerMinute = "ui.graph.per-minute";
    public const string PerHour = "ui.graph.per-hour";
    public const string Arrange = UIGraphWords.Arrange;
    public const string Save = UIGraphWords.Save;
    public const string GroupSelection = UIGraphWords.GroupSelection;
    public const string DeleteSelection = UIGraphWords.DeleteSelection;
    public const string DeleteEdge = UIGraphWords.DeleteEdge;
    public const string Pinned = UIGraphWords.Pinned;
    public const string Rename = UIGraphWords.Rename;
    public const string Color = UIGraphWords.Color;
    public const string DefaultColor = UIGraphWords.DefaultColor;
    public const string AddReroute = UIGraphWords.AddReroute;
    public const string ResetNodeState = UIGraphWords.ResetNodeState;
    public const string Caption = UIGraphWords.Caption;
    public const string TakeServer = UIGraphWords.TakeServer;
    public const string KeepMine = UIGraphWords.KeepMine;
    public const string AddResource = UIGraphWords.AddResource;
    public const string CraftTime = UIGraphWords.CraftTime;
    public const string Bought = UIGraphWords.Bought;
    public const string Takes = UIGraphWords.Takes;
    public const string Gives = UIGraphWords.Gives;
    public const string LinkIngredient = UIGraphWords.LinkIngredient;
    public const string LinkRecipe = UIGraphWords.LinkRecipe;
    public const string Blue = UIGraphWords.Blue;
    public const string Amber = UIGraphWords.Amber;
    public const string Green = UIGraphWords.Green;
    public const string Rose = UIGraphWords.Rose;
    public const string Purple = UIGraphWords.Purple;
    public const string Cyan = UIGraphWords.Cyan;
    public const string Bronze = UIGraphWords.Bronze;
    public const string Fern = UIGraphWords.Fern;

    /// <inheritdoc/>
    public IReadOnlyDictionary<string, string> English { get; } = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [Canvas] = "Node canvas",
        [AddNode] = "Add node",
        [SearchKinds] = "Search kinds",
        [NoKinds] = "No node kinds match",
        [Categories] = "Categories",
        [AllKinds] = "All",
        [Uncategorized] = "Other",
        [ZoomIn] = "Zoom in",
        [ZoomOut] = "Zoom out",
        [Fit] = "Fit to content",
        [Menu] = "Canvas menu",
        [Minimap] = "Map of the sheet",
        [Log] = "Log",
        [ClearLog] = "Clear the log",
        [LogEmpty] = "Nothing has been written yet",
        [RunProgress] = "Run progress",
        [PinMany] = "{type}, several",
        [PinType] = "{name} ({type})",
        [TypeAny] = "anything",
        [TypeList] = "list",
        [TypeListOf] = "{type} list",
        [TypeText] = "text",
        [TypeNumber] = "number",
        [TypeBoolean] = "yes or no",
        [TypeImage] = "picture",
        [TypeDate] = "date",
        [TypeTime] = "time",
        [TypeDateTime] = "date and time",
        [Percent] = "{value}%",
        [DisplayField] = "{key}: {value}",
        [Run] = "Run",
        [RunAll] = "Run all",
        [Stop] = "Stop",
        [RunLine] = "{node} · {message}",
        [RunRequired] = "'{pin}' is required.",
        [RunStopped] = "Stopped.",
        [RunCycle] = "The node is on a cycle: it waits for itself.",
        [FileProgress] = "{index} of {total}: {name}.",
        [Collapse] = "Fold",
        [Expand] = "Unfold",
        [Pin] = "Pin",
        [Unpin] = "Unpin",
        [Group] = "Group",
        [NewNode] = "New node",
        [NewResource] = "New resource",
        [Recipe] = "Recipe",
        [Remove] = "Remove",
        [AddValue] = "Add",
        [ResetState] = "Start over",
        [NoValue] = "Nothing yet",
        [More] = "… {count} more",
        [ChooseFile] = "Choose a picture",
        [AddParameter] = "Add to parameters",
        [RemoveParameter] = "Remove from parameters",
        [ResetPin] = "Reset",
        [Parameters] = "Parameters",
        [ParametersEmpty] = "Add an input from its menu to set it out here",
        [ShowNode] = "Show the node",
        [UploadFailed] = "Upload failed",
        [Unsaved] = "Unsaved",
        [Saving] = "Saving…",
        [Plan] = "Plan",
        [PlanTargets] = "Targets",
        [AddTarget] = "Add target",
        [SearchResources] = "Search resources",
        [NoResources] = "No resources match",
        [Target] = "Target",
        [Period] = "Counted",
        [PeriodOnce] = "Once",
        [PeriodMinute] = "Every minute",
        [PeriodHour] = "Every hour",
        [Objective] = "Make least",
        [LeastRaw] = "What is brought in",
        [LeastTime] = "The time",
        [LeastCost] = "The cost",
        [PlanEmpty] = "Name a resource to plan for with Add target; the sheet draws what it takes.",
        [PlanInfeasible] = "No runs reach these targets: a cycle takes more than it gives.",
        [PlanUnsettled] = "No plan could be settled for these targets.",
        [PlanTotals] = "Time {time} · brought in {raw} · cost {cost}",
        [PlanBroughtIn] = "Brought in",
        [PlanResources] = "Resources",
        [PlanCrafts] = "Recipes",
        [PlanResource] = "Resource",
        [PlanAmount] = "Amount",
        [PlanMade] = "Made",
        [PlanTaken] = "Taken",
        [PlanLeft] = "Left over",
        [PlanRuns] = "Runs",
        [PlanTime] = "Time",
        [PlanWorkers] = "Workers",
        [PlanAtOnce] = "{count} at once",
        [PerMinute] = "/min",
        [PerHour] = "/h",
        [Arrange] = "Arrange",
        [Save] = "Save",
        [GroupSelection] = "Group selection",
        [DeleteSelection] = "Delete selection",
        [DeleteEdge] = "Delete",
        [Pinned] = "Pinned",
        [Rename] = "Rename",
        [Color] = "Color",
        [DefaultColor] = "Default",
        [AddReroute] = "Add reroute",
        [ResetNodeState] = "Reset",
        [Caption] = "Caption",
        [TakeServer] = "Take the server's",
        [KeepMine] = "Keep mine",
        [AddResource] = "Add resource",
        [CraftTime] = "Time",
        [Bought] = "Brought in",
        [Takes] = "Takes",
        [Gives] = "Gives",
        [LinkIngredient] = "Add as an ingredient",
        [LinkRecipe] = "New recipe",
        [Blue] = "Blue",
        [Amber] = "Amber",
        [Green] = "Green",
        [Rose] = "Rose",
        [Purple] = "Purple",
        [Cyan] = "Cyan",
        [Bronze] = "Bronze",
        [Fern] = "Fern"
    }.ToFrozenDictionary(StringComparer.Ordinal);
}
